# Generated by Django 2.2.24 on 2021-12-16 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20211213_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 12, 33, 48, 958920, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
